export const memories = [
  {
    id: 1,
    type: "image",
    src: "/images/card_1.webp",
    caption: "Jab Shehar Naya Tha, Aur Tu Mila...",
    sub: "Anjaan AMU ki galiyon mein pehla apna insaan — 2022",
    accent: "magenta",
    songTitle: "Jagjit Singh Ghazal",
    songArtist: "Jagjit Singh Classic",
    audioKey: "jagjit",
  },
  {
    id: 2,
    type: "image",
    src: "/images/card_2.jpg",
    caption: "Chup Si Muskaan, Bematlab Ki Yaari",
    sub: "Bina bole sab samajhna, bas wahi toh sachhi dosti hai 💖",
    accent: "violet",
    songTitle: "Chand Lamhe",
    songArtist: "Memorable Vibe",
    audioKey: "chandlamhe",
  },
  {
    id: 3,
    type: "image",
    src: "/images/card_3.webp",
    caption: "Raat Ke 2 Baje Ki Maggi Aur Sapne",
    sub: "Saari duniya so rahi thi, aur hum apne sapne bun rahe the 🌙",
    accent: "cyan",
    songTitle: "Bin Kahe",
    songArtist: "Late Night Vibe",
    audioKey: "binkahe",
  },
  {
    id: 4,
    type: "image",
    src: "/images/card_4.jpg",
    caption: "Teen Jism, Ek Dhadkan",
    sub: "Wo gang jo hostel ke kamre ko ghar bana deti thi 🏠✨",
    accent: "gold",
    songTitle: "Jab Lagaawelu Tu Lipastic",
    songArtist: "Bhojpuri High Energy Hit",
    audioKey: "lipstick",
  },
  {
    id: 5,
    type: "image",
    src: "/images/card_5.png",
    caption: "Do Yaar, Hazaaron Yaadein",
    sub: "Saal badal gaye, par teri meri yaari bilkul nahi badli 🤝",
    accent: "magenta",
    songTitle: "Tere Jaisa Yaar Kahan",
    songArtist: "Yaarana Vibe",
    audioKey: "terejaisa",
  },
  {
    id: 6,
    type: "image",
    src: "/images/card_6.png",
    caption: "Jeet Ki Khushi, Har Gham Mein Saath",
    sub: "Jab tu muskuraata hai, lagta hai poori duniya jeet li 👑",
    accent: "gold",
    songTitle: "Janeman Jaane Jigar",
    songArtist: "Classic Hit Vibe",
    audioKey: "janeman",
  },
  {
    id: 7,
    type: "image",
    src: "/images/card_7.png",
    caption: "Kacche Raste, Pukhta Dosti",
    sub: "Safar kitna bhi lamba ho, tere saath pata nahi chalta ✈️",
    accent: "cyan",
    songTitle: "Instagram Reel Track",
    songArtist: "Safar Vibe (Reel 27402)",
    audioKey: "jungle",
  },
  {
    id: 8,
    type: "image",
    src: "/images/card_8.png",
    caption: "Jangal Mein Rasta Khoya, Magar Tu Saath Tha",
    sub: "Darr nahi tha, kyunki pata tha mera bhai aage chal raha hai 🌲",
    accent: "violet",
    songTitle: "Yun Hi Chala Chala Rahi",
    songArtist: "Wanderlust Beats",
    audioKey: "yunhichala",
  },
  {
    id: 9,
    type: "image",
    src: "/images/card_9.png",
    caption: "Bulandiyon Par Stand Lene Wala Yaar",
    sub: "Choti par pahunch kar pehli nazar tujhe khojti hai 🏔️",
    accent: "cyan",
    songTitle: "Senorita / ZNMD Vibe",
    songArtist: "Zindagi Na Milegi Dobara",
    audioKey: "senorita",
  },
  {
    id: 10,
    type: "image",
    src: "/images/card_10.png",
    caption: "Sapno Ke Sang, Kot-Pant Mein Mera Bhai",
    sub: "Tujhe kamyaab dekhna hi meri sabse badi khushi hai 🎯💼",
    accent: "magenta",
    songTitle: "Lakshya Toh Har Haal Mein Paana Hai",
    songArtist: "Chasing Big Dreams",
    audioKey: "lakshya",
  },
  {
    id: 11,
    type: "image",
    src: "/images/card_11.jpg",
    caption: "Gharm Chai Aur Dil Ki Baatein",
    sub: "Thandhi hawa, chai ki chuski, aur mera sabse purana yaar ☕",
    accent: "gold",
    songTitle: "Tere Jaisa Yaar Kahan",
    songArtist: "Yaarana Vibe",
    audioKey: "terejaisa",
  },
  {
    id: 12,
    type: "image",
    src: "/images/card_12.jpg",
    caption: "Nadi Ke Kinare, Humari Dosti Ka Aaina",
    sub: "Jaise behti nadi shaant hai, waise hi humari dosti sachhi hai 🌊",
    accent: "cyan",
    songTitle: "Instagram Reel Track",
    songArtist: "River Vibe (Reel 50230)",
    audioKey: "reelaudio50230",
  },
];

export const wishes = [
  "Happy Birthday Mithlesh 💖",
  "Mera Pehla & Sabse Sachha Dost 🤝",
  "Forever Grateful For You 👑",
  "AMU Se IIT Tak Ka Shandaar Safar 🚀",
  "Dosti Zindabad Hamesha 🎉",
  "Tu Hai Toh Sab Kuch Hai Mere Bhai ✨",
];

export const friendshipQuotes = [
  {
    hi: "Jab koi nahi tha, tab tu tha.",
    en: "When no one was there, you were.",
  },
  {
    hi: "College ke pehle din se aaj tak — tu mera sabse sachha bhai hai.",
    en: "From the first day of college till today, you have been my true brother.",
  },
  {
    hi: "Har hansi, har struggle, har jeet — sab tere saath hai.",
    en: "Every laugh, every struggle, every victory — all with you.",
  },
];
