export const memories = [
  {
    id: 1,
    type: "image",
    src: "/images/card_1.webp",
    caption: "Jahaan se dosti shuru hui",
    sub: "Where our story began — 2022",
    accent: "magenta",
    songTitle: "Jagjit Singh Ghazal",
    songArtist: "Jagjit Singh Classic",
    audioKey: "jagjit",
  },
  {
    id: 2,
    type: "image",
    src: "/images/card_2.jpg",
    caption: "Chup si muskaan, gehri dosti",
    sub: "Some frames stay forever",
    accent: "violet",
    songTitle: "Chand Lamhe",
    songArtist: "Memorable Vibe",
    audioKey: "chandlamhe",
  },
  {
    id: 3,
    type: "image",
    src: "/images/card_3.webp",
    caption: "Raat ke us pal wale yaar",
    sub: "Late nights, endless laughs",
    accent: "cyan",
    songTitle: "Bin Kahe",
    songArtist: "Late Night Vibe",
    audioKey: "binkahe",
  },
  {
    id: 4,
    type: "image",
    src: "/images/card_4.jpg",
    caption: "Teen dost, ek hi dil",
    sub: "The gang that felt like home",
    accent: "gold",
    songTitle: "Jab Lagaawelu Tu Lipastic",
    songArtist: "Bhojpuri High Energy Hit",
    audioKey: "lipstick",
  },
  {
    id: 5,
    type: "image",
    src: "/images/card_5.png",
    caption: "Do yaar, ek muskaan",
    sub: "Bonds that only got stronger",
    accent: "magenta",
    songTitle: "Tere Jaisa Yaar Kahan",
    songArtist: "Yaarana Vibe",
    audioKey: "terejaisa",
  },
  {
    id: 6,
    type: "image",
    src: "/images/card_6.png",
    caption: "Jeet humesha saath mein",
    sub: "Winning, together — always",
    accent: "gold",
    songTitle: "Janeman Jaane Jigar",
    songArtist: "Classic Hit Vibe",
    audioKey: "janeman",
  },
  {
    id: 7,
    type: "image",
    src: "/images/card_7.png",
    caption: "Safar ke saathi",
    sub: "Every adventure, side by side",
    accent: "cyan",
    songTitle: "Instagram Reel Track",
    songArtist: "Safar Vibe (Reel 27402)",
    audioKey: "jungle",
  },
  {
    id: 8,
    type: "image",
    src: "/images/card_8.png",
    caption: "Rasto par khoya, khud ko paaya",
    sub: "Lost in the woods, found in memories",
    accent: "violet",
    songTitle: "Yun Hi Chala Chala Rahi",
    songArtist: "Wanderlust Beats",
    audioKey: "yunhichala",
  },
  {
    id: 9,
    type: "image",
    src: "/images/card_9.png",
    caption: "Bulandiyon ka yaar",
    sub: "Reaching new heights",
    accent: "cyan",
    songTitle: "Senorita / ZNMD Vibe",
    songArtist: "Zindagi Na Milegi Dobara",
    audioKey: "senorita",
  },
  {
    id: 10,
    type: "image",
    src: "/images/card_10.png",
    caption: "Sapno ke peeche daudta mera yaar",
    sub: "Dressed for the dreams he chases",
    accent: "magenta",
    songTitle: "Lakshya Toh Har Haal Mein Paana Hai",
    songArtist: "Chasing Big Dreams",
    audioKey: "lakshya",
  },
  {
    id: 11,
    type: "image",
    src: "/images/card_11.jpg",
    caption: "Muskurahat aur yaari",
    sub: "Chai, baatein, aur sachha yaar",
    accent: "gold",
    songTitle: "Tere Jaisa Yaar Kahan",
    songArtist: "Yaarana Vibe",
    audioKey: "terejaisa",
  },
  {
    id: 12,
    type: "image",
    src: "/images/card_12.jpg",
    caption: "Nadi kinare, suhaana safar",
    sub: "Standing tall by the river",
    accent: "cyan",
    songTitle: "Instagram Reel Track",
    songArtist: "River Vibe (Reel 50230)",
    audioKey: "reelaudio50230",
  },
];

export const wishes = [
  "Happy Birthday Mithlesh",
  "Mere pehle dost",
  "Forever Grateful",
  "AMU se IIT tak",
  "Dosti Zindabad",
  "Tu hai toh sab hai",
];

export const friendshipQuotes = [
  {
    hi: "Jab koi nahi tha, tu tha.",
    en: "When no one was there, you were.",
  },
  {
    hi: "College ke pehle din se aaj tak — tu wahi hai.",
    en: "From the first day of college till today, you never changed.",
  },
  {
    hi: "Har hansi, har struggle, har jeet — sab tere saath.",
    en: "Every laugh, every fight, every win — all with you.",
  },
];
